import type { WordDeck } from '@/types'

export const WORD_DECKS: WordDeck[] = [
  {
    id: 'none',
    name: 'デッキなし',
    description: '従来の方式で問題生成',
    emoji: '🎯',
    cardCount: 0,
    difficulty: 'beginner',
    category: 'general',
    cards: [],
  },
  {
    id: 'japanese-basics',
    name: 'Japanese Basics',
    description: '日本語基礎表現',
    emoji: '🇯🇵',
    cardCount: 15,
    difficulty: 'beginner',
    category: 'daily',
    cards: [
      { id: '1', japanese: 'おはようございます', english: 'Good morning' },
      { id: '2', japanese: 'ありがとうございます', english: 'Thank you' },
      { id: '3', japanese: 'すみません', english: 'Excuse me / Sorry' },
      { id: '4', japanese: 'はじめまして', english: 'Nice to meet you' },
      { id: '5', japanese: 'お疲れ様でした', english: 'Good work / Good job' },
      { id: '6', japanese: 'どうぞよろしくお願いします', english: 'Please treat me favorably' },
      { id: '7', japanese: 'いただきます', english: 'Thank you for the meal (before eating)' },
      { id: '8', japanese: 'ごちそうさまでした', english: 'Thank you for the meal (after eating)' },
      { id: '9', japanese: 'お元気ですか', english: 'How are you?' },
      { id: '10', japanese: 'さようなら', english: 'Goodbye' },
      { id: '11', japanese: 'お先に失礼します', english: 'Excuse me for leaving first' },
      { id: '12', japanese: 'いらっしゃいませ', english: 'Welcome (to a store)' },
      { id: '13', japanese: 'お久しぶりです', english: 'Long time no see' },
      { id: '14', japanese: 'がんばってください', english: 'Good luck / Do your best' },
      {
        id: '15',
        japanese: 'お世話になっております',
        english: 'Thank you for your continued support',
      },
    ],
  },
  {
    id: 'travel-phrases',
    name: 'Travel Phrases',
    description: '旅行で使える英会話',
    emoji: '✈️',
    cardCount: 20,
    difficulty: 'beginner',
    category: 'travel',
    cards: [
      { id: '1', japanese: 'チェックインをお願いします', english: "I'd like to check in, please" },
      {
        id: '2',
        japanese: '空港までどのくらいかかりますか',
        english: 'How long does it take to get to the airport?',
      },
      { id: '3', japanese: '道に迷いました', english: "I'm lost" },
      { id: '4', japanese: 'おすすめの料理は何ですか', english: 'What do you recommend?' },
      { id: '5', japanese: 'お会計をお願いします', english: 'Could I have the bill, please?' },
      {
        id: '6',
        japanese: '写真を撮っていただけますか',
        english: 'Could you take a photo for me?',
      },
      {
        id: '7',
        japanese: 'wifi のパスワードを教えてください',
        english: 'Could you tell me the wifi password?',
      },
      { id: '8', japanese: '予約をしています', english: 'I have a reservation' },
      {
        id: '9',
        japanese: 'タクシーを呼んでいただけますか',
        english: 'Could you call a taxi for me?',
      },
      { id: '10', japanese: '両替はどこでできますか', english: 'Where can I exchange money?' },
      { id: '11', japanese: '近くに ATM はありますか', english: 'Is there an ATM nearby?' },
      { id: '12', japanese: 'お土産を探しています', english: "I'm looking for souvenirs" },
      { id: '13', japanese: '地図をもらえますか', english: 'Could I get a map?' },
      {
        id: '14',
        japanese: '観光地への行き方を教えてください',
        english: 'Could you tell me how to get to tourist attractions?',
      },
      { id: '15', japanese: 'この電車は○○に行きますか', english: 'Does this train go to ○○?' },
      {
        id: '16',
        japanese: '荷物を預けることはできますか',
        english: 'Can I leave my luggage here?',
      },
      { id: '17', japanese: '営業時間を教えてください', english: 'What are your opening hours?' },
      { id: '18', japanese: '入場料はいくらですか', english: 'How much is the admission fee?' },
      { id: '19', japanese: 'ここは写真撮影は可能ですか', english: 'Is photography allowed here?' },
      { id: '20', japanese: '最寄りの駅はどこですか', english: 'Where is the nearest station?' },
    ],
  },
  {
    id: 'food-vocabulary',
    name: 'Food Vocabulary',
    description: '食べ物関連の語彙',
    emoji: '🍔',
    cardCount: 12,
    difficulty: 'beginner',
    category: 'food',
    cards: [
      { id: '1', japanese: 'これは何ですか', english: 'What is this?' },
      { id: '2', japanese: 'アレルギーがあります', english: 'I have allergies' },
      {
        id: '3',
        japanese: 'ベジタリアン用の料理はありますか',
        english: 'Do you have vegetarian dishes?',
      },
      {
        id: '4',
        japanese: '辛くないものをお願いします',
        english: "I'd like something not spicy, please",
      },
      { id: '5', japanese: 'おかわりをお願いします', english: 'Could I have a refill, please?' },
      { id: '6', japanese: 'とても美味しいです', english: "It's very delicious" },
      { id: '7', japanese: 'お腹がいっぱいです', english: "I'm full" },
      { id: '8', japanese: 'テイクアウトでお願いします', english: "I'd like it to go, please" },
      { id: '9', japanese: 'メニューを見せてください', english: 'Could I see the menu, please?' },
      { id: '10', japanese: '水をください', english: 'Could I have some water, please?' },
      { id: '11', japanese: 'お箸をもらえますか', english: 'Could I have chopsticks?' },
      { id: '12', japanese: 'お持ち帰り用の袋をください', english: 'Could I have a takeout bag?' },
    ],
  },
]

export const DEFAULT_DECK = WORD_DECKS[0]
