import { Header } from '@/components'
import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Quick Eigo',
  description: 'Generated by Quick Eigo',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className="flex min-h-screen flex-col bg-gray-100">
        <Header />
        {children}
      </body>
    </html>
  )
}
